development:
  adapter: postgresql
  database: db/bookshelf_pg_dev
  username: postgres
  password: unix11
  pool: 5
  timeout: 5000
  
test:
  adapter: postgresql
  database: db/bookshelf_pg_test
  username: postgres
  password: unix11
  pool: 5
  timeout: 5000
